// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: sensors.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Car {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sensors: [Sensor] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sensor {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Sensor.SensorType {
    get {return _storage._type ?? .camera}
    set {_uniqueStorage()._type = newValue}
  }
  /// Returns true if `type` has been explicitly set.
  var hasType: Bool {return _storage._type != nil}
  /// Clears the value of `type`. Subsequent reads from it will return its default value.
  mutating func clearType() {_storage._type = nil}

  var translation: Sensor.Translate {
    get {return _storage._translation ?? Sensor.Translate()}
    set {_uniqueStorage()._translation = newValue}
  }
  /// Returns true if `translation` has been explicitly set.
  var hasTranslation: Bool {return _storage._translation != nil}
  /// Clears the value of `translation`. Subsequent reads from it will return its default value.
  mutating func clearTranslation() {_storage._translation = nil}

  var rotation: Sensor.Rotate {
    get {return _storage._rotation ?? Sensor.Rotate()}
    set {_uniqueStorage()._rotation = newValue}
  }
  /// Returns true if `rotation` has been explicitly set.
  var hasRotation: Bool {return _storage._rotation != nil}
  /// Clears the value of `rotation`. Subsequent reads from it will return its default value.
  mutating func clearRotation() {_storage._rotation = nil}

  var cameraParams: Sensor.CameraParams {
    get {return _storage._cameraParams ?? Sensor.CameraParams()}
    set {_uniqueStorage()._cameraParams = newValue}
  }
  /// Returns true if `cameraParams` has been explicitly set.
  var hasCameraParams: Bool {return _storage._cameraParams != nil}
  /// Clears the value of `cameraParams`. Subsequent reads from it will return its default value.
  mutating func clearCameraParams() {_storage._cameraParams = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum SensorType: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case camera // = 0

    init() {
      self = .camera
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .camera
      default: return nil
      }
    }

    var rawValue: Int {
      switch self {
      case .camera: return 0
      }
    }

  }

  struct Translate {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Axis defined to be positive out of camera.
    var x: Double {
      get {return _x ?? 0}
      set {_x = newValue}
    }
    /// Returns true if `x` has been explicitly set.
    var hasX: Bool {return self._x != nil}
    /// Clears the value of `x`. Subsequent reads from it will return its default value.
    mutating func clearX() {self._x = nil}

    var y: Double {
      get {return _y ?? 0}
      set {_y = newValue}
    }
    /// Returns true if `y` has been explicitly set.
    var hasY: Bool {return self._y != nil}
    /// Clears the value of `y`. Subsequent reads from it will return its default value.
    mutating func clearY() {self._y = nil}

    var z: Double {
      get {return _z ?? 0}
      set {_z = newValue}
    }
    /// Returns true if `z` has been explicitly set.
    var hasZ: Bool {return self._z != nil}
    /// Clears the value of `z`. Subsequent reads from it will return its default value.
    mutating func clearZ() {self._z = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _x: Double? = nil
    fileprivate var _y: Double? = nil
    fileprivate var _z: Double? = nil
  }

  struct Rotate {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var x: Double {
      get {return _x ?? 0}
      set {_x = newValue}
    }
    /// Returns true if `x` has been explicitly set.
    var hasX: Bool {return self._x != nil}
    /// Clears the value of `x`. Subsequent reads from it will return its default value.
    mutating func clearX() {self._x = nil}

    var y: Double {
      get {return _y ?? 0}
      set {_y = newValue}
    }
    /// Returns true if `y` has been explicitly set.
    var hasY: Bool {return self._y != nil}
    /// Clears the value of `y`. Subsequent reads from it will return its default value.
    mutating func clearY() {self._y = nil}

    var z: Double {
      get {return _z ?? 0}
      set {_z = newValue}
    }
    /// Returns true if `z` has been explicitly set.
    var hasZ: Bool {return self._z != nil}
    /// Clears the value of `z`. Subsequent reads from it will return its default value.
    mutating func clearZ() {self._z = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _x: Double? = nil
    fileprivate var _y: Double? = nil
    fileprivate var _z: Double? = nil
  }

  struct CameraParams {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Supplied in radians.
    var fov: Double {
      get {return _storage._fov ?? 0}
      set {_uniqueStorage()._fov = newValue}
    }
    /// Returns true if `fov` has been explicitly set.
    var hasFov: Bool {return _storage._fov != nil}
    /// Clears the value of `fov`. Subsequent reads from it will return its default value.
    mutating func clearFov() {_storage._fov = nil}

    var focalLength: Double {
      get {return _storage._focalLength ?? 0}
      set {_uniqueStorage()._focalLength = newValue}
    }
    /// Returns true if `focalLength` has been explicitly set.
    var hasFocalLength: Bool {return _storage._focalLength != nil}
    /// Clears the value of `focalLength`. Subsequent reads from it will return its default value.
    mutating func clearFocalLength() {_storage._focalLength = nil}

    var imageSize: Sensor.CameraParams.ImageSize {
      get {return _storage._imageSize ?? Sensor.CameraParams.ImageSize()}
      set {_uniqueStorage()._imageSize = newValue}
    }
    /// Returns true if `imageSize` has been explicitly set.
    var hasImageSize: Bool {return _storage._imageSize != nil}
    /// Clears the value of `imageSize`. Subsequent reads from it will return its default value.
    mutating func clearImageSize() {_storage._imageSize = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    struct ImageSize {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var width: Int32 {
        get {return _width ?? 0}
        set {_width = newValue}
      }
      /// Returns true if `width` has been explicitly set.
      var hasWidth: Bool {return self._width != nil}
      /// Clears the value of `width`. Subsequent reads from it will return its default value.
      mutating func clearWidth() {self._width = nil}

      var height: Int32 {
        get {return _height ?? 0}
        set {_height = newValue}
      }
      /// Returns true if `height` has been explicitly set.
      var hasHeight: Bool {return self._height != nil}
      /// Clears the value of `height`. Subsequent reads from it will return its default value.
      mutating func clearHeight() {self._height = nil}

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}

      fileprivate var _width: Int32? = nil
      fileprivate var _height: Int32? = nil
    }

    init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Car: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Car"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "sensors"),
  ]

  public var isInitialized: Bool {
    if !SwiftProtobuf.Internal.areAllInitialized(self.sensors) {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.sensors)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sensors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.sensors, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: Car) -> Bool {
    if self.sensors != other.sensors {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Sensor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Sensor"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
    2: .same(proto: "translation"),
    3: .same(proto: "rotation"),
    4: .standard(proto: "camera_params"),
  ]

  fileprivate class _StorageClass {
    var _type: Sensor.SensorType? = nil
    var _translation: Sensor.Translate? = nil
    var _rotation: Sensor.Rotate? = nil
    var _cameraParams: Sensor.CameraParams? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _type = source._type
      _translation = source._translation
      _rotation = source._rotation
      _cameraParams = source._cameraParams
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._type == nil {return false}
      if let v = _storage._cameraParams, !v.isInitialized {return false}
      return true
    }
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularEnumField(value: &_storage._type)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._translation)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._rotation)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._cameraParams)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._type {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
      }
      if let v = _storage._translation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if let v = _storage._rotation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if let v = _storage._cameraParams {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: Sensor) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._type != other_storage._type {return false}
        if _storage._translation != other_storage._translation {return false}
        if _storage._rotation != other_storage._rotation {return false}
        if _storage._cameraParams != other_storage._cameraParams {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Sensor.SensorType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CAMERA"),
  ]
}

extension Sensor.Translate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Sensor.protoMessageName + ".Translate"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "x"),
    2: .same(proto: "y"),
    3: .same(proto: "z"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularDoubleField(value: &self._x)
      case 2: try decoder.decodeSingularDoubleField(value: &self._y)
      case 3: try decoder.decodeSingularDoubleField(value: &self._z)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._x {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    }
    if let v = self._y {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 2)
    }
    if let v = self._z {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: Sensor.Translate) -> Bool {
    if self._x != other._x {return false}
    if self._y != other._y {return false}
    if self._z != other._z {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Sensor.Rotate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Sensor.protoMessageName + ".Rotate"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "x"),
    2: .same(proto: "y"),
    3: .same(proto: "z"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularDoubleField(value: &self._x)
      case 2: try decoder.decodeSingularDoubleField(value: &self._y)
      case 3: try decoder.decodeSingularDoubleField(value: &self._z)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._x {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    }
    if let v = self._y {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 2)
    }
    if let v = self._z {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: Sensor.Rotate) -> Bool {
    if self._x != other._x {return false}
    if self._y != other._y {return false}
    if self._z != other._z {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Sensor.CameraParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Sensor.protoMessageName + ".CameraParams"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "fov"),
    2: .standard(proto: "focal_length"),
    3: .standard(proto: "image_size"),
  ]

  fileprivate class _StorageClass {
    var _fov: Double? = nil
    var _focalLength: Double? = nil
    var _imageSize: Sensor.CameraParams.ImageSize? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _fov = source._fov
      _focalLength = source._focalLength
      _imageSize = source._imageSize
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._fov == nil {return false}
      if _storage._focalLength == nil {return false}
      if _storage._imageSize == nil {return false}
      if let v = _storage._imageSize, !v.isInitialized {return false}
      return true
    }
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularDoubleField(value: &_storage._fov)
        case 2: try decoder.decodeSingularDoubleField(value: &_storage._focalLength)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._imageSize)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._fov {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
      }
      if let v = _storage._focalLength {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 2)
      }
      if let v = _storage._imageSize {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: Sensor.CameraParams) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._fov != other_storage._fov {return false}
        if _storage._focalLength != other_storage._focalLength {return false}
        if _storage._imageSize != other_storage._imageSize {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Sensor.CameraParams.ImageSize: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Sensor.CameraParams.protoMessageName + ".ImageSize"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "width"),
    2: .same(proto: "height"),
  ]

  public var isInitialized: Bool {
    if self._width == nil {return false}
    if self._height == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self._width)
      case 2: try decoder.decodeSingularInt32Field(value: &self._height)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._width {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    }
    if let v = self._height {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: Sensor.CameraParams.ImageSize) -> Bool {
    if self._width != other._width {return false}
    if self._height != other._height {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
